### ISSUE TITLE
forgerock-guava removed in AM 6.5

### ISSUE THREAD

**Issue by AndyReynolds1** [ForgeRock/ip-address-decision-auth-tree-node#1]
As per the following knowledge base article:  https://backstage.forgerock.com/knowledge/kb/article/a49666598

Does this need updating to reflect the forgerock-guava has been removed in AM 6.5?

> The dependency on forgerock-guava has been removed in AM 6.5 and instead these libraries are retrieved directly from Google Guava. For example, all the node .java files have been updated as follows:

```
import com.google.common.collect.ImmutableList;
//import org.forgerock.guava.common.collect.ImmutableList;
```

Functionality seems to continue to work, but using the node in the UI becomes broken in AM 6.5.x.

**Comment by smof** [comment]
Resolved by 052fce9d7dd846d1724a81b0f1edf96d41f63a30
